x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 5s
  retries: 10
  start_period: 1s

services:
  alice:
    build: .
    container_name: alice
    environment:
      D3TN_AAP2_KEY: "my_extremely_secret_secret_omg_i_love_this_secretly_secret_secret"
    networks:
      - charon
    command:
      - /app/build/charon
      - /app/conf/charon.conf
    cap_add:
      - NET_ADMIN
    volumes:
      - ./alice/:/app/conf/
    devices:
      - /dev/net/tun
    profiles:
      - tests
    depends_on:
      ud3tn-config-rx:
        condition: service_completed_successfully
      ud3tn-config:
        condition: service_completed_successfully
  bob:
    build: .
    container_name: bob
    environment:
      D3TN_AAP2_KEY: "my_extremely_secret_secret_omg_i_love_this_secretly_secret_secret"
    networks:
      - charon
    cap_add:
      - NET_ADMIN
    command:
      - /app/build/charon
      - /app/conf/charon.conf
    volumes:
      - ./bob:/app/conf/
    devices:
      - /dev/net/tun
    profiles:
      - tests
    depends_on:
      ud3tn-config-rx:
        condition: service_completed_successfully
      ud3tn-config:
        condition: service_completed_successfully

  alice-ud3tn:
    image: ud3tn:exp-debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - charon
    ports:
      - 4225:4225
    environment:
      AAP2_SECRET: "my_extremely_secret_secret_omg_i_love_this_secretly_secret_secret"
    command:
      - --allow-remote-config
      - -b
      - "7"
      - -c
      - "mtcp:*,4224"
      - -e
      - dtn://alice.dtn/
      - -l
      - "86400"
      - -L
      - "4"
      - -m
      - "0"
      - -P
      - "4225"
      - -A
      - 0.0.0.0
      - -x
      - "AAP2_SECRET"
    healthcheck:
      test: ["CMD-SHELL", "pgrep ud3tn > /dev/null || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 1
      start_period: 1s
  bob-ud3tn:
    image: ud3tn:exp-debug
    networks:
      - charon
    environment:
      AAP2_SECRET: "my_extremely_secret_secret_omg_i_love_this_secretly_secret_secret"
    command:
      - --allow-remote-config
      - -b
      - "7"
      - -c
      - "mtcp:*,4224"
      - -e
      - dtn://bob.dtn/
      - -l
      - "86400"
      - -L
      - "4"
      - -m
      - "0"
      - -P
      - "4225"
      - -A
      - 0.0.0.0
      - -x
      - "AAP2_SECRET"
    healthcheck:
      test: ["CMD-SHELL", "pgrep ud3tn > /dev/null || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 1
      start_period: 1s
  ud3tn-config:
    image: ud3tn-python:exp
    networks:
      - charon
    environment:
      AAP2_SECRET: "my_extremely_secret_secret_omg_i_love_this_secretly_secret_secret"
    command:
      - /usr/local/bin/aap2-config
      - --tcp
      - alice-ud3tn
      - "4225"
      - --secret-var
      - AAP2_SECRET
      - --schedule
      - "1"
      - "3600000"
      - "100000"
      - dtn://bob.dtn/
      - "mtcp:bob-ud3tn:4224"
    depends_on:
      alice-ud3tn:
        condition: service_healthy
      bob-ud3tn:
        condition: service_healthy
  ud3tn-config-rx:
    image: ud3tn-python:exp
    networks:
      - charon
    environment:
      AAP2_SECRET: "my_extremely_secret_secret_omg_i_love_this_secretly_secret_secret"
    command:
      - /usr/local/bin/aap2-config
      - --tcp
      - bob-ud3tn
      - "4225"
      - --secret-var
      - AAP2_SECRET
      - --schedule
      - "1"
      - "3600000"
      - "100000"
      - dtn://alice.dtn/
      - "mtcp:alice-ud3tn:4224"
    depends_on:
      alice-ud3tn:
        condition: service_healthy
      bob-ud3tn:
        condition: service_healthy

networks:
  charon:
    driver: bridge
